version: '3.1'

services:
  server:
    build:
      context: ./server/
    command: ['npm', 'run', 'start:dev']
    ports:
      - '9229:9229'
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
    env_file:
      - './server/.env'
    depends_on:
      - db
      - redis
  db:
    build:
      context: ./db/
    ports:
      - '5432:5432'
    env_file:
      - './db/.env'
  redis:
    build:
      context: ./redis/
    ports:
      - '6379:6379'
