version: '3.1'

services:
  server:
    build:
      context: ./server/
    command: ['npm', 'run', 'start:dev']
    ports:
      - '9229:9229'
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
