version: '3.1'

services:
  server:
    build:
      context: ./server/
    command: ['npm', 'run', 'start:dev']
    ports:
      - '9229:9229'
      - '3000:3000'
    volumes:
      - ./server:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=gqltest
      - DB_USER=postgres
      - DB_PASS=postgres
      - SALT_ROUNDS=10
      - SECRET=ThisIsSomethingReallySecret!?#
    depends_on:
      - db
      - redis
  db:
    build:
      context: ./db/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gqltest
  redis:
    build:
      context: ./redis/
    ports:
      - '6379:6379'
