/* tslint:disable */
import { GraphQLResolveInfo } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface GQLQuery {
  user: GQLUserType | null;
}

export interface GQLUserType {
  age: number | null;
  firstName: string | null;
  id: string | null;
}

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface GQLResolver {
  Query?: GQLQueryTypeResolver;
  UserType?: GQLUserTypeTypeResolver;
}
export interface GQLQueryTypeResolver<TParent = any> {
  user?: QueryToUserResolver<TParent>;
}

export interface QueryToUserArgs {
  id: string;
  firstName?: string;
}
export interface QueryToUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: QueryToUserArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface GQLUserTypeTypeResolver<TParent = any> {
  age?: UserTypeToAgeResolver<TParent>;
  firstName?: UserTypeToFirstNameResolver<TParent>;
  id?: UserTypeToIdResolver<TParent>;
}

export interface UserTypeToAgeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserTypeToFirstNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserTypeToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
